// Terms of Service markup generated by Termly (static copy, pasted 2026-06-19).
// Rendered as-is on /terms via dangerouslySetInnerHTML. To update, regenerate in
// Termly and replace this string. Cleaned of Termly's editor artifacts.
export const TERMS_HTML = String.raw`<style>
  [data-custom-class='body'], [data-custom-class='body'] * { background: transparent !important; }
[data-custom-class='title'], [data-custom-class='title'] * { font-family: Arial !important; font-size: 26px !important; color: #000000 !important; }
[data-custom-class='subtitle'], [data-custom-class='subtitle'] * { font-family: Arial !important; color: #595959 !important; font-size: 14px !important; }
[data-custom-class='heading_1'], [data-custom-class='heading_1'] * { font-family: Arial !important; font-size: 19px !important; color: #000000 !important; }
[data-custom-class='heading_2'], [data-custom-class='heading_2'] * { font-family: Arial !important; font-size: 17px !important; color: #000000 !important; }
[data-custom-class='body_text'], [data-custom-class='body_text'] * { color: #595959 !important; font-size: 14px !important; font-family: Arial !important; }
[data-custom-class='link'], [data-custom-class='link'] * { color: #3030F1 !important; font-size: 14px !important; font-family: Arial !important; word-break: break-word !important; }
ul { list-style-type: square; }
ul > li > ul { list-style-type: circle; }
ul > li > ul > li > ul { list-style-type: square; }
ol li { font-family: Arial; }
</style>
<div data-custom-class="body">
<div data-custom-class="title"><h1>TERMS OF SERVICE</h1></div>
<div data-custom-class="subtitle"><strong>Last updated</strong> <strong>July 21, 2026</strong></div>
<br>
<div data-custom-class="heading_1"><h2>AGREEMENT TO OUR LEGAL TERMS</h2></div>
<div data-custom-class="body_text">We are SmartProps LLC ("<strong>Company</strong>," "<strong>we</strong>," "<strong>us</strong>," "<strong>our</strong>"), a company registered in California, United States.</div>
<br>
<div data-custom-class="body_text">We operate the website <a target="_blank" data-custom-class="link" href="https://app.smartprops.io">https://app.smartprops.io</a> (the "<strong>Site</strong>"), as well as any other related products and services that refer or link to these legal terms (the "<strong>Legal Terms</strong>") (collectively, the "<strong>Services</strong>").</div>
<br>
<div data-custom-class="body_text">SmartProps is a cloud-based, multi-tenant software-as-a-service (SaaS) platform that enables businesses to build, manage, and send professional proposals and price quotes to their clients. Users can maintain a product/service catalog, create multi-scenario quotes, author proposal documents, preview and generate PDFs, and send proposals for electronic signature. The service is accessed through a web browser and stores customer-provided data (such as client contact details and proposal content) to provide these features.</div>
<br>
<div data-custom-class="body_text">You can contact us by email at <a target="_blank" data-custom-class="link" href="mailto:hello@smartprops.io">hello@smartprops.io</a>.</div>
<br>
<div data-custom-class="body_text">These Legal Terms constitute a legally binding agreement made between you, whether personally or on behalf of an entity ("<strong>you</strong>"), and SmartProps LLC, concerning your access to and use of the Services. You agree that by accessing the Services, you have read, understood, and agreed to be bound by all of these Legal Terms. IF YOU DO NOT AGREE WITH ALL OF THESE LEGAL TERMS, THEN YOU ARE EXPRESSLY PROHIBITED FROM USING THE SERVICES AND YOU MUST DISCONTINUE USE IMMEDIATELY.</div>
<br>
<div data-custom-class="body_text">We will notify users by posting the updated Legal Terms on this page with a new "Last updated" date. For material changes, we may also notify users by email. Your continued use of the Services after the updated terms become effective constitutes acceptance of the changes.</div>
<br>
<div data-custom-class="body_text">The Services are intended for users who are at least 18 years old. Persons under the age of 18 are not permitted to use or register for the Services.</div>
<br>
<div data-custom-class="body_text">We recommend that you print a copy of these Legal Terms for your records.</div>
<br>
<div data-custom-class="heading_1"><h2>TABLE OF CONTENTS</h2></div>
<div><a data-custom-class="link" href="#services">1. OUR SERVICES</a></div>
<div><a data-custom-class="link" href="#ip">2. INTELLECTUAL PROPERTY RIGHTS</a></div>
<div><a data-custom-class="link" href="#userreps">3. USER REPRESENTATIONS</a></div>
<div><a data-custom-class="link" href="#userreg">4. USER REGISTRATION</a></div>
<div><a data-custom-class="link" href="#purchases">5. PURCHASES AND PAYMENT</a></div>
<div><a data-custom-class="link" href="#prohibited">6. PROHIBITED ACTIVITIES</a></div>
<div><a data-custom-class="link" href="#ugc">7. USER GENERATED CONTRIBUTIONS</a></div>
<div><a data-custom-class="link" href="#license">8. CONTRIBUTION LICENSE</a></div>
<div><a data-custom-class="link" href="#thirdparty">9. THIRD-PARTY WEBSITES AND CONTENT</a></div>
<div><a data-custom-class="link" href="#sitemanage">10. SERVICES MANAGEMENT</a></div>
<div><a data-custom-class="link" href="#ppyes">11. PRIVACY POLICY</a></div>
<div><a data-custom-class="link" href="#copyrightyes">12. COPYRIGHT INFRINGEMENTS</a></div>
<div><a data-custom-class="link" href="#terms">13. TERM AND TERMINATION</a></div>
<div><a data-custom-class="link" href="#modifications">14. MODIFICATIONS AND INTERRUPTIONS</a></div>
<div><a data-custom-class="link" href="#law">15. GOVERNING LAW</a></div>
<div><a data-custom-class="link" href="#disputes">16. DISPUTE RESOLUTION</a></div>
<div><a data-custom-class="link" href="#corrections">17. CORRECTIONS</a></div>
<div><a data-custom-class="link" href="#disclaimer">18. DISCLAIMER</a></div>
<div><a data-custom-class="link" href="#liability">19. LIMITATIONS OF LIABILITY</a></div>
<div><a data-custom-class="link" href="#indemnification">20. INDEMNIFICATION</a></div>
<div><a data-custom-class="link" href="#userdata">21. USER DATA</a></div>
<div><a data-custom-class="link" href="#electronic">22. ELECTRONIC COMMUNICATIONS, TRANSACTIONS, AND SIGNATURES</a></div>
<div><a data-custom-class="link" href="#california">23. CALIFORNIA USERS AND RESIDENTS</a></div>
<div><a data-custom-class="link" href="#misc">24. MISCELLANEOUS</a></div>
<div><a data-custom-class="link" href="#addclause">25. BETA AND EVALUATION SERVICE</a></div>
<div><a data-custom-class="link" href="#addclauseb">26. NON-BINDING ELECTRONIC SIGNATURES DURING EVALUATION</a></div>
<div><a data-custom-class="link" href="#addclausec">27. YOUR CONTENT AND THIRD-PARTY DATA</a></div>
<div><a data-custom-class="link" href="#contact">28. CONTACT US</a></div>
<br>
<div data-custom-class="heading_1" id="services"><h2>1. OUR SERVICES</h2></div>
<div data-custom-class="body_text">The information provided when using the Services is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation or which would subject us to any registration requirement within such jurisdiction or country. Accordingly, those persons who choose to access the Services from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable.</div>
<br>
<div data-custom-class="body_text">The Services are not tailored to comply with industry-specific regulations (Health Insurance Portability and Accountability Act (HIPAA), Federal Information Security Management Act (FISMA), etc.), so if your interactions would be subjected to such laws, you may not use the Services. You may not use the Services in a way that would violate the Gramm-Leach-Bliley Act (GLBA).</div>
<br>
<div data-custom-class="heading_1" id="ip"><h2>2. INTELLECTUAL PROPERTY RIGHTS</h2></div>
<div data-custom-class="heading_2"><h3>Our intellectual property</h3></div>
<div data-custom-class="body_text">We are the owner or the licensee of all intellectual property rights in our Services, including all source code, databases, functionality, software, website designs, audio, video, text, photographs, and graphics in the Services (collectively, the "Content"), as well as the trademarks, service marks, and logos contained therein (the "Marks").</div>
<br>
<div data-custom-class="body_text">Our Content and Marks are protected by copyright and trademark laws (and various other intellectual property rights and unfair competition laws) and treaties in the United States and around the world.</div>
<br>
<div data-custom-class="body_text">The Content and Marks are provided in or through the Services "AS IS" for your internal business purpose only.</div>
<div data-custom-class="heading_2"><h3>Your use of our Services</h3></div>
<div data-custom-class="body_text">Subject to your compliance with these Legal Terms, including the "PROHIBITED ACTIVITIES" section below, we grant you a non-exclusive, non-transferable, revocable license to: (a) access the Services; and (b) download or print a copy of any portion of the Content to which you have properly gained access, solely for your internal business purpose.</div>
<br>
<div data-custom-class="body_text">Except as set out in this section or elsewhere in our Legal Terms, no part of the Services and no Content or Marks may be copied, reproduced, aggregated, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted, distributed, sold, licensed, or otherwise exploited for any commercial purpose whatsoever, without our express prior written permission.</div>
<br>
<div data-custom-class="body_text">If you wish to make any use of the Services, Content, or Marks other than as set out in this section or elsewhere in our Legal Terms, please address your request to: <a target="_blank" data-custom-class="link" href="mailto:hello@smartprops.io">hello@smartprops.io</a>.</div>
<br>
<div data-custom-class="body_text">We reserve all rights not expressly granted to you in and to the Services, Content, and Marks. Any breach of these Intellectual Property Rights will constitute a material breach of our Legal Terms and your right to use our Services will terminate immediately.</div>
<div data-custom-class="heading_2"><h3>Your submissions and contributions</h3></div>
<div data-custom-class="body_text">Please review this section and the "PROHIBITED ACTIVITIES" section carefully prior to using our Services to understand the (a) rights you give us and (b) obligations you have when you post or upload any content through the Services.</div>
<br>
<div data-custom-class="body_text"><strong>Submissions:</strong> By directly sending us any question, comment, suggestion, idea, feedback, or other information about the Services ("Submissions"), you agree to assign to us all intellectual property rights in such Submission. You agree that we shall own this Submission and be entitled to its unrestricted use and dissemination for any lawful purpose, commercial or otherwise, without acknowledgment or compensation to you.</div>
<br>
<div data-custom-class="body_text"><strong>Contributions:</strong> The Services may invite you to chat, contribute to, or participate in blogs, message boards, online forums, and other functionality during which you may create, submit, post, display, transmit, publish, distribute, or broadcast content and materials to us or through the Services ("Contributions").</div>
<br>
<div data-custom-class="body_text"><strong>You are responsible for what you post or upload:</strong> You confirm that you have read and agree with our "PROHIBITED ACTIVITIES" and will not post content that is illegal, harassing, hateful, harmful, defamatory, obscene, bullying, abusive, discriminatory, threatening, sexually explicit, false, inaccurate, deceitful, or misleading; you warrant that any such Submission and/or Contributions are original to you or that you have the necessary rights and licenses; and you are solely responsible for your Submissions and/or Contributions and agree to reimburse us for any losses we may suffer because of your breach of this section, any third party's intellectual property rights, or applicable law.</div>
<br>
<div data-custom-class="body_text"><strong>We may remove or edit your Content:</strong> Although we have no obligation to monitor any Contributions, we shall have the right to remove or edit any Contributions at any time without notice if in our reasonable opinion we consider such Contributions harmful or in breach of these Legal Terms.</div>
<div data-custom-class="heading_2"><h3>Copyright infringement</h3></div>
<div data-custom-class="body_text">We respect the intellectual property rights of others. If you believe that any material available on or through the Services infringes upon any copyright you own or control, please immediately refer to the "COPYRIGHT INFRINGEMENTS" section below.</div>
<br>
<div data-custom-class="heading_1" id="userreps"><h2>3. USER REPRESENTATIONS</h2></div>
<div data-custom-class="body_text">By using the Services, you represent and warrant that: (1) all registration information you submit will be true, accurate, current, and complete; (2) you will maintain the accuracy of such information and promptly update such registration information as necessary; (3) you have the legal capacity and you agree to comply with these Legal Terms; (4) you are not a minor in the jurisdiction in which you reside; (5) you will not access the Services through automated or non-human means, whether through a bot, script or otherwise; (6) you will not use the Services for any illegal or unauthorized purpose; and (7) your use of the Services will not violate any applicable law or regulation.</div>
<br>
<div data-custom-class="body_text">If you provide any information that is untrue, inaccurate, not current, or incomplete, we have the right to suspend or terminate your account and refuse any and all current or future use of the Services (or any portion thereof).</div>
<br>
<div data-custom-class="heading_1" id="userreg"><h2>4. USER REGISTRATION</h2></div>
<div data-custom-class="body_text">You may be required to register to use the Services. You agree to keep your password confidential and will be responsible for all use of your account and password. We reserve the right to remove, reclaim, or change a username you select if we determine, in our sole discretion, that such username is inappropriate, obscene, or otherwise objectionable.</div>
<br>
<div data-custom-class="heading_1" id="purchases"><h2>5. PURCHASES AND PAYMENT</h2></div>
<div data-custom-class="body_text">The Services are currently provided free of charge. If we introduce paid features, you agree to provide current, complete, and accurate purchase and account information for all purchases, and we will update these Legal Terms accordingly. We reserve the right to refuse any order and to correct any errors or mistakes in pricing.</div>
<br>
<div data-custom-class="heading_1" id="prohibited"><h2>6. PROHIBITED ACTIVITIES</h2></div>
<div data-custom-class="body_text">You may not access or use the Services for any purpose other than that for which we make the Services available. As a user of the Services, you agree not to:</div>
<ul>
<li data-custom-class="body_text">Systematically retrieve data or other content from the Services to create or compile, directly or indirectly, a collection, compilation, database, or directory without written permission from us.</li>
<li data-custom-class="body_text">Trick, defraud, or mislead us and other users, especially in any attempt to learn sensitive account information such as user passwords.</li>
<li data-custom-class="body_text">Circumvent, disable, or otherwise interfere with security-related features of the Services.</li>
<li data-custom-class="body_text">Disparage, tarnish, or otherwise harm, in our opinion, us and/or the Services.</li>
<li data-custom-class="body_text">Use any information obtained from the Services in order to harass, abuse, or harm another person.</li>
<li data-custom-class="body_text">Make improper use of our support services or submit false reports of abuse or misconduct.</li>
<li data-custom-class="body_text">Use the Services in a manner inconsistent with any applicable laws or regulations.</li>
<li data-custom-class="body_text">Engage in unauthorized framing of or linking to the Services.</li>
<li data-custom-class="body_text">Upload or transmit viruses, Trojan horses, or other material that interferes with any party's uninterrupted use and enjoyment of the Services or modifies, impairs, disrupts, alters, or interferes with the use, features, functions, operation, or maintenance of the Services.</li>
<li data-custom-class="body_text">Engage in any automated use of the system, such as using scripts, data mining, robots, or similar data gathering and extraction tools.</li>
<li data-custom-class="body_text">Delete the copyright or other proprietary rights notice from any Content.</li>
<li data-custom-class="body_text">Attempt to impersonate another user or person or use the username of another user.</li>
<li data-custom-class="body_text">Interfere with, disrupt, or create an undue burden on the Services or the networks or services connected to the Services.</li>
<li data-custom-class="body_text">Harass, annoy, intimidate, or threaten any of our employees or agents engaged in providing any portion of the Services to you.</li>
<li data-custom-class="body_text">Attempt to bypass any measures of the Services designed to prevent or restrict access to the Services.</li>
<li data-custom-class="body_text">Copy or adapt the Services' software, or decipher, decompile, disassemble, or reverse engineer any of the software, except as permitted by applicable law.</li>
<li data-custom-class="body_text">Make any unauthorized use of the Services, including collecting usernames and/or email addresses by electronic means for the purpose of sending unsolicited email, or creating user accounts by automated means or under false pretenses.</li>
<li data-custom-class="body_text">Use the Services as part of any effort to compete with us or otherwise use the Services and/or the Content for any revenue-generating endeavor or commercial enterprise (other than the intended use of creating and sending your own proposals/quotes).</li>
<li data-custom-class="body_text">Sell or otherwise transfer your profile.</li>
<li data-custom-class="body_text">Upload, submit, or process personal information about third parties (such as your clients or contacts) without the legal right and any necessary consents to do so.</li>
<li data-custom-class="body_text">Use the electronic-signature features to forge, falsify, impersonate, or create documents you are not authorized to create, or to obtain a signature through deception.</li>
<li data-custom-class="body_text">Attempt to access, interfere with, or disrupt data, accounts, or workspaces belonging to other customers, or otherwise circumvent the multi-tenant separation of the Services.</li>
<li data-custom-class="body_text">Use any AI-powered features to generate unlawful, infringing, deceptive, or harmful content.</li>
</ul>
<div data-custom-class="heading_1" id="ugc"><h2>7. USER GENERATED CONTRIBUTIONS</h2></div>
<div data-custom-class="body_text">The Services may provide you with the opportunity to create, submit, post, display, transmit, perform, publish, distribute, or broadcast content and materials to us or on the Services ("Contributions"). When you create or make available any Contributions, you represent and warrant that: your Contributions do not infringe the proprietary rights of any third party; you are the creator and owner of or have the necessary licenses, rights, consents, and permissions to use and authorize us to use your Contributions; your Contributions are not false, inaccurate, or misleading; your Contributions are not unsolicited or unauthorized advertising, spam, or other forms of solicitation; your Contributions are not obscene, harassing, defamatory, or otherwise objectionable; and your Contributions do not violate any applicable law, regulation, or rule, or the privacy or publicity rights of any third party. Any use of the Services in violation of the foregoing may result in termination or suspension of your rights to use the Services.</div>
<br>
<div data-custom-class="heading_1" id="license"><h2>8. CONTRIBUTION LICENSE</h2></div>
<div data-custom-class="body_text">You and the Services agree that we may access, store, process, and use any information and personal data that you provide and your choices (including settings), solely as necessary to host and operate the Services and provide them to you. We do not assert any ownership over your Contributions. You retain full ownership of all of your Contributions and any intellectual property rights or other proprietary rights associated with your Contributions. Any license you grant us is limited to hosting, storing, processing, and displaying your Contributions as necessary to provide the Services to you, and (where you place a pricing table, signature field, or similar) to deliver proposals to the recipients you choose. We do not use your Contributions for advertising or marketing without your permission.</div>
<br>
<div data-custom-class="heading_1" id="thirdparty"><h2>9. THIRD-PARTY WEBSITES AND CONTENT</h2></div>
<div data-custom-class="body_text">The Services may contain (or you may be sent via the Site) links to other websites ("Third-Party Websites") as well as content belonging to or originating from third parties ("Third-Party Content"). Such Third-Party Websites and Third-Party Content are not investigated, monitored, or checked for accuracy, appropriateness, or completeness by us, and we are not responsible for any Third-Party Websites accessed through the Services or any Third-Party Content. Inclusion of, linking to, or permitting the use of any Third-Party Websites or Content does not imply approval or endorsement by us. If you access Third-Party Websites or use Third-Party Content, you do so at your own risk, and these Legal Terms no longer govern.</div>
<br>
<div data-custom-class="heading_1" id="sitemanage"><h2>10. SERVICES MANAGEMENT</h2></div>
<div data-custom-class="body_text">We reserve the right, but not the obligation, to: (1) monitor the Services for violations of these Legal Terms; (2) take appropriate legal action against anyone who, in our sole discretion, violates the law or these Legal Terms; (3) refuse, restrict access to, limit the availability of, or disable any of your Contributions or any portion thereof; (4) remove from the Services or otherwise disable all files and content that are excessive in size or are in any way burdensome to our systems; and (5) otherwise manage the Services in a manner designed to protect our rights and property and to facilitate the proper functioning of the Services.</div>
<br>
<div data-custom-class="heading_1" id="ppyes"><h2>11. PRIVACY POLICY</h2></div>
<div data-custom-class="body_text">We care about data privacy and security. Please review our Privacy Policy: <strong><a target="_blank" data-custom-class="link" href="https://app.smartprops.io/privacy-policy">https://app.smartprops.io/privacy-policy</a></strong>. By using the Services, you agree to be bound by our Privacy Policy, which is incorporated into these Legal Terms. Please be advised the Services are hosted in the United States. By continuing to use the Services, you consent to have your data transferred to and processed in the United States.</div>
<br>
<div data-custom-class="heading_1" id="copyrightyes"><h2>12. COPYRIGHT INFRINGEMENTS</h2></div>
<div data-custom-class="body_text">We respect the intellectual property rights of others. If you believe that any material available on or through the Services infringes upon any copyright you own or control, please immediately notify us using the contact information provided below (a "Notification"). A copy of your Notification will be sent to the person who posted or stored the material addressed in the Notification. Please be advised that pursuant to applicable law you may be held liable for damages if you make material misrepresentations in a Notification.</div>
<br>
<div data-custom-class="heading_1" id="terms"><h2>13. TERM AND TERMINATION</h2></div>
<div data-custom-class="body_text">These Legal Terms shall remain in full force and effect while you use the Services. WITHOUT LIMITING ANY OTHER PROVISION OF THESE LEGAL TERMS, WE RESERVE THE RIGHT TO, IN OUR SOLE DISCRETION AND WITHOUT NOTICE OR LIABILITY, DENY ACCESS TO AND USE OF THE SERVICES (INCLUDING BLOCKING CERTAIN IP ADDRESSES), TO ANY PERSON FOR ANY REASON OR FOR NO REASON. WE MAY TERMINATE YOUR USE OR PARTICIPATION IN THE SERVICES OR DELETE YOUR ACCOUNT AND ANY CONTENT OR INFORMATION THAT YOU POSTED AT ANY TIME, WITHOUT WARNING, IN OUR SOLE DISCRETION.</div>
<br>
<div data-custom-class="body_text">If we terminate or suspend your account for any reason, you are prohibited from registering and creating a new account under your name, a fake or borrowed name, or the name of any third party.</div>
<br>
<div data-custom-class="heading_1" id="modifications"><h2>14. MODIFICATIONS AND INTERRUPTIONS</h2></div>
<div data-custom-class="body_text">We reserve the right to change, modify, or remove the contents of the Services at any time or for any reason at our sole discretion without notice. We will not be liable to you or any third party for any modification, price change, suspension, or discontinuance of the Services. We cannot guarantee the Services will be available at all times. You agree that we have no liability whatsoever for any loss, damage, or inconvenience caused by your inability to access or use the Services during any downtime or discontinuance of the Services.</div>
<br>
<div data-custom-class="heading_1" id="law"><h2>15. GOVERNING LAW</h2></div>
<div data-custom-class="body_text">These Legal Terms and your use of the Services are governed by and construed in accordance with the laws of the State of California applicable to agreements made and to be entirely performed within the State of California, without regard to its conflict of law principles.</div>
<br>
<div data-custom-class="heading_1" id="disputes"><h2>16. DISPUTE RESOLUTION</h2></div>
<div data-custom-class="heading_2"><h3>Informal Negotiations</h3></div>
<div data-custom-class="body_text">To expedite resolution and control the cost of any dispute, controversy, or claim related to these Legal Terms (each a "Dispute" and collectively, the "Disputes") brought by either you or us (individually, a "Party" and collectively, the "Parties"), the Parties agree to first attempt to negotiate any Dispute (except those Disputes expressly provided below) informally for at least thirty (30) days before initiating arbitration. Such informal negotiations commence upon written notice from one Party to the other Party.</div>
<div data-custom-class="heading_2"><h3>Binding Arbitration</h3></div>
<div data-custom-class="body_text">If the Parties are unable to resolve a Dispute through informal negotiations, the Dispute (except those Disputes expressly excluded below) will be finally and exclusively resolved by binding arbitration. YOU UNDERSTAND THAT WITHOUT THIS PROVISION, YOU WOULD HAVE THE RIGHT TO SUE IN COURT AND HAVE A JURY TRIAL. The arbitration shall be commenced and conducted under the Commercial Arbitration Rules of the American Arbitration Association ("AAA") and, where appropriate, the AAA's Supplementary Procedures for Consumer Related Disputes ("AAA Consumer Rules"), both of which are available at the <a data-custom-class="link" href="http://www.adr.org" rel="noopener noreferrer" target="_blank">American Arbitration Association (AAA) website</a>. Your arbitration fees and your share of arbitrator compensation shall be governed by the AAA Consumer Rules and, where appropriate, limited by the AAA Consumer Rules. If such costs are determined by the arbitrator to be excessive, we will pay all arbitration fees and expenses. The arbitration may be conducted in person, through the submission of documents, by phone, or online. Except where otherwise required by the applicable AAA rules or applicable law, the arbitration will take place in Alameda, California.</div>
<br>
<div data-custom-class="body_text">If for any reason, a Dispute proceeds in court rather than arbitration, the Dispute shall be commenced or prosecuted in the state and federal courts located in Alameda, California, and the Parties hereby consent to, and waive all defenses of lack of personal jurisdiction, and forum non conveniens with respect to venue and jurisdiction in such state and federal courts.</div>
<br>
<div data-custom-class="body_text">In no event shall any Dispute brought by either Party related in any way to the Services be commenced more than one (1) years after the cause of action arose.</div>
<div data-custom-class="heading_2"><h3>Restrictions</h3></div>
<div data-custom-class="body_text">The Parties agree that any arbitration shall be limited to the Dispute between the Parties individually. To the full extent permitted by law, (a) no arbitration shall be joined with any other proceeding; (b) there is no right or authority for any Dispute to be arbitrated on a class-action basis or to utilize class action procedures; and (c) there is no right or authority for any Dispute to be brought in a purported representative capacity on behalf of the general public or any other persons.</div>
<div data-custom-class="heading_2"><h3>Exceptions to Informal Negotiations and Arbitration</h3></div>
<div data-custom-class="body_text">The Parties agree that the following Disputes are not subject to the above provisions concerning informal negotiations and binding arbitration: (a) any Disputes seeking to enforce or protect, or concerning the validity of, any of the intellectual property rights of a Party; (b) any Dispute related to, or arising from, allegations of theft, piracy, invasion of privacy, or unauthorized use; and (c) any claim for injunctive relief.</div>
<br>
<div data-custom-class="heading_1" id="corrections"><h2>17. CORRECTIONS</h2></div>
<div data-custom-class="body_text">There may be information on the Services that contains typographical errors, inaccuracies, or omissions, including descriptions, pricing, availability, and various other information. We reserve the right to correct any errors, inaccuracies, or omissions and to change or update the information on the Services at any time, without prior notice.</div>
<br>
<div data-custom-class="heading_1" id="disclaimer"><h2>18. DISCLAIMER</h2></div>
<div data-custom-class="body_text">THE SERVICES ARE PROVIDED ON AN AS-IS AND AS-AVAILABLE BASIS. YOU AGREE THAT YOUR USE OF THE SERVICES WILL BE AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE SERVICES AND YOUR USE THEREOF, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE MAKE NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THE SERVICES' CONTENT AND WE WILL ASSUME NO LIABILITY OR RESPONSIBILITY FOR ANY ERRORS, MISTAKES, OR INACCURACIES OF CONTENT, ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY PERSONAL INFORMATION STORED THEREIN, ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE SERVICES, OR ANY BUGS, VIRUSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE SERVICES BY ANY THIRD PARTY. AS WITH THE PURCHASE OF A PRODUCT OR SERVICE THROUGH ANY MEDIUM OR IN ANY ENVIRONMENT, YOU SHOULD USE YOUR BEST JUDGMENT AND EXERCISE CAUTION WHERE APPROPRIATE.</div>
<br>
<div data-custom-class="heading_1" id="liability"><h2>19. LIMITATIONS OF LIABILITY</h2></div>
<div data-custom-class="body_text">IN NO EVENT WILL WE OR OUR DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DIRECT, INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFIT, LOST REVENUE, LOSS OF DATA, OR OTHER DAMAGES ARISING FROM YOUR USE OF THE SERVICES, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, OUR LIABILITY TO YOU FOR ANY CAUSE WHATSOEVER AND REGARDLESS OF THE FORM OF THE ACTION, WILL AT ALL TIMES BE LIMITED TO $100.00 USD. CERTAIN US STATE LAWS AND INTERNATIONAL LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS.</div>
<br>
<div data-custom-class="heading_1" id="indemnification"><h2>20. INDEMNIFICATION</h2></div>
<div data-custom-class="body_text">You agree to defend, indemnify, and hold us harmless, including our subsidiaries, affiliates, and all of our respective officers, agents, partners, and employees, from and against any loss, damage, liability, claim, or demand, including reasonable attorneys' fees and expenses, made by any third party due to or arising out of: (1) your Contributions; (2) use of the Services; (3) breach of these Legal Terms; (4) any breach of your representations and warranties set forth in these Legal Terms; (5) your violation of the rights of a third party, including but not limited to intellectual property rights; or (6) any overt harmful act toward any other user of the Services with whom you connected via the Services.</div>
<br>
<div data-custom-class="heading_1" id="userdata"><h2>21. USER DATA</h2></div>
<div data-custom-class="body_text">We will maintain certain data that you transmit to the Services for the purpose of managing the performance of the Services, as well as data relating to your use of the Services. Although we perform regular routine backups of data, you are solely responsible for all data that you transmit or that relates to any activity you have undertaken using the Services. You agree that we shall have no liability to you for any loss or corruption of any such data, and you hereby waive any right of action against us arising from any such loss or corruption of such data.</div>
<br>
<div data-custom-class="heading_1" id="electronic"><h2>22. ELECTRONIC COMMUNICATIONS, TRANSACTIONS, AND SIGNATURES</h2></div>
<div data-custom-class="body_text">Visiting the Services, sending us emails, and completing online forms constitute electronic communications. You consent to receive electronic communications, and you agree that all agreements, notices, disclosures, and other communications we provide to you electronically, via email and on the Services, satisfy any legal requirement that such communication be in writing. YOU HEREBY AGREE TO THE USE OF ELECTRONIC SIGNATURES, CONTRACTS, ORDERS, AND OTHER RECORDS, AND TO ELECTRONIC DELIVERY OF NOTICES, POLICIES, AND RECORDS OF TRANSACTIONS INITIATED OR COMPLETED BY US OR VIA THE SERVICES.</div>
<br>
<div data-custom-class="heading_1" id="california"><h2>23. CALIFORNIA USERS AND RESIDENTS</h2></div>
<div data-custom-class="body_text">If any complaint with us is not satisfactorily resolved, you can contact the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs in writing at 1625 North Market Blvd., Suite N 112, Sacramento, California 95834 or by telephone at (800) 952-5210 or (916) 445-1254.</div>
<br>
<div data-custom-class="heading_1" id="misc"><h2>24. MISCELLANEOUS</h2></div>
<div data-custom-class="body_text">These Legal Terms and any policies or operating rules posted by us on the Services or in respect to the Services constitute the entire agreement and understanding between you and us. Our failure to exercise or enforce any right or provision of these Legal Terms shall not operate as a waiver of such right or provision. These Legal Terms operate to the fullest extent permissible by law. We may assign any or all of our rights and obligations to others at any time. We shall not be responsible or liable for any loss, damage, delay, or failure to act caused by any cause beyond our reasonable control. If any provision or part of a provision of these Legal Terms is determined to be unlawful, void, or unenforceable, that provision or part of the provision is deemed severable from these Legal Terms and does not affect the validity and enforceability of any remaining provisions. There is no joint venture, partnership, employment or agency relationship created between you and us as a result of these Legal Terms or use of the Services.</div>
<br>
<div data-custom-class="heading_1" id="addclause"><h2>25. BETA AND EVALUATION SERVICE</h2></div>
<div data-custom-class="body_text">SmartProps is currently provided on a free demo, evaluation, and beta basis. The Services are provided "AS IS" and "AS AVAILABLE," may contain errors or be interrupted, and may change or be discontinued at any time without notice. You use the Services at your own risk and should not rely on them as your sole system of record.</div>
<br>
<div data-custom-class="heading_1" id="addclauseb"><h2>26. NON-BINDING ELECTRONIC SIGNATURES DURING EVALUATION</h2></div>
<div data-custom-class="body_text">The Services include electronic-signature features (provided via a third-party e-signature provider). During the demo, evaluation, and beta period, any proposal, quote, or document signed through the Services is provided for testing and evaluation purposes only and is NOT intended to create a legally binding contract or enforceable obligation between you and your clients or any other party. Do not use the Services to execute agreements you intend to be legally binding during this period. You are solely responsible for independently executing any binding agreement through appropriate legal means.</div>
<br>
<div data-custom-class="heading_1" id="addclausec"><h2>27. YOUR CONTENT AND THIRD-PARTY DATA</h2></div>
<div data-custom-class="body_text">You are responsible for the data you submit, including personal information about your own clients and contacts, and for ensuring you have the right and any necessary consents to provide that data to us and to send proposals to your clients.</div>
<br>
<div data-custom-class="heading_1" id="contact"><h2>28. CONTACT US</h2></div>
<div data-custom-class="body_text">In order to resolve a complaint regarding the Services or to receive further information regarding use of the Services, please contact us at:</div>
<br>
<div data-custom-class="body_text"><strong>SmartProps LLC</strong></div>
<div data-custom-class="body_text"><strong><a target="_blank" data-custom-class="link" href="mailto:hello@smartprops.io">hello@smartprops.io</a></strong></div>
<br>
<div data-custom-class="body_text">These Terms of Service were created using Termly's <a href="https://termly.io/products/terms-and-conditions-generator/" target="_blank" rel="noopener external" data-custom-class="link">Terms and Conditions Generator</a>.</div>
</div>`;
